### ISSUE TITLE
npm start: throw er; // Unhandled 'error' event; gulp

### ISSUE THREAD

**Issue by AlexVFornazieri** [paulsutherland/Polyonic#12]
Hello guys,

I again, I managed to run the 'npm install', but now I can not get 'npm start' and start the application, the error log follows:
(...)
[22:37:23] Using gulpfile ~/Polyonic/gulpfile.js
[22:37:23] Starting 'clean'...
[22:37:23] Starting 'watch'...
[22:37:23] Finished 'watch' after 13 ms
[22:37:23] Finished 'clean' after 38 ms
[22:37:23] Starting 'bundle'...
[22:37:23] Starting 'copy'...
[22:37:23] Starting 'finalize'...
[22:37:23] Finished 'finalize' after 1.62 ms
[22:37:23] Finished 'bundle' after 63 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/abelha/Polyonic/src/node_modules/babel-runtime/core-js/array/find-index.js ENOSPC
    at exports._errnoException (util.js:1018:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/home/abelha/Polyonic/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/abelha/Polyonic/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/abelha/Polyonic/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/abelha/Polyonic/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/abelha/Polyonic/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! polyonic@1.0.0 start: `gulp start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polyonic@1.0.0 start script 'gulp start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the polyonic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs polyonic
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls polyonic
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/abelha/Polyonic/npm-debug.log

**Comment by jean-merelis** [comment]
See issue #8

**Comment by paulsutherland** [comment]
@AlexVFornazieri 

To work around this, you will need to increase the number of file watchers to allow gulp to work.

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

I have updated the README to reference this ENOSPC issue.
