### ISSUE TITLE
Error: Uncaught (in promise): ReferenceError: electron is not defined

### ISSUE THREAD

**Issue by amciver** [paulsutherland/Polyonic#15]
When running _ionic serve_ via src directory, it is unable to locate the _electron_ const with the stack noted below. _npm start_ does successfully work in loading the electron application.

Error: Uncaught (in promise): ReferenceError: electron is not defined
ReferenceError: electron is not defined
    at new HomePage (http://localhost:8103/build/main.js:55843:52)
    at createClass (http://localhost:8103/build/main.js:11170:26)
    at createDirectiveInstance (http://localhost:8103/build/main.js:11001:37)
    at createViewNodes (http://localhost:8103/build/main.js:12364:49)
    at createRootView (http://localhost:8103/build/main.js:12269:5)
    at callWithDebugContext (http://localhost:8103/build/main.js:13484:42)
    at Object.debugCreateRootView [as createRootView] (http://localhost:8103/build/main.js:12944:12)
    at ComponentFactory_.create (http://localhost:8103/build/main.js:10190:46)
    at ComponentFactoryBoundToModule.create (http://localhost:8103/build/main.js:3726:29)
    at Tab.NavControllerBase._viewInit (http://localhost:8103/build/main.js:43898:44)
    at c (http://localhost:8103/build/polyfills.js:3:13190)
    at Object.reject (http://localhost:8103/build/polyfills.js:3:12546)
    at Tab.NavControllerBase._fireError (http://localhost:8103/build/main.js:43656:16)
    at Tab.NavControllerBase._failed (http://localhost:8103/build/main.js:43644:14)
    at http://localhost:8103/build/main.js:43699:59
    at t.invoke (http://localhost:8103/build/polyfills.js:3:8971)
    at Object.onInvoke (http://localhost:8103/build/main.js:4427:37)
    at t.invoke (http://localhost:8103/build/polyfills.js:3:8911)
    at r.run (http://localhost:8103/build/polyfills.js:3:4140)
    at http://localhost:8103/build/polyfills.js:3:13731

**Comment by madlybong** [comment]
As you can see there are 2 _'src'_ folders...
First one is for the _electron_ and second one is _ionic_ so if you run _ionic serve_ in the second folder the _electron_ is unavailable where as the first _src_ folder will use _electron_ to serve all your _ionic/ angular_ code.

**Comment by paulsutherland** [comment]
@amciver 
Hi, sorry for the delay I was on a summer holiday.

Yes that is correct.  If you are in the src folder running ionic commands, then you are not running the app as an electron apo, so you would need to comment out:

```
  <script>
      const electron  = require('electron');
      const path      = require('path');
      const ipc       = require('electron').ipcMain
  </script>
```

In the index.html file.

And in this example, remove:

```
declare const electron
declare const path
```

from the src/pages/home/home.ts file.

So as @madlybong pointed out, you would be running plain Ionic as either a hybrid app or a progressive web app.

To get the use of electron you run the npm scripts from the top level directory.

If you look in the index.html file you'll see the following:

```
  <!-- cordova.js required for cordova apps -->
  <!--<script src="cordova.js"></script>-->

  <!-- un-comment this code for Node.JS integration in Ionic for Electron, we load the Node packages here-->
  <script>
      const electron  = require('electron');
      const path      = require('path');
      const ipc       = require('electron').ipcMain
  </script>

  <!-- un-comment this code to enable service worker
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('service-worker.js')
        .then(() => console.log('service worker installed'))
        .catch(err => console.error('Error', err));
    }
  </script>-->

```

You comment out or remove what is not required based upon whether you want to run a desktop electron app, cordova app or progressive web app.

Thanks,

Paul

**Comment by amciver** [comment]
@paulsutherland Got it! All is working as expected now!
